travis:
  secure:
    BINSTAR_TOKEN: CrGWaxFHGAvFcJ81My0eH+agQoCsYf8a0DFNnYl+h9O1tgQ4YtR4g3MkvBR7hoZV1QLq2wmY4m8teEPwEbMYBE4APjT43/6eNT8ir1Za7lhccth5OU9hZvrdIrIGdtnjDZBLnhA+6UmKqg6zVyQ+2lBEQMLObdK1G4SMYKTMz7QsLraV4KYeeeZCLZ2DHoYQS1Dx9A8EobKG6GNuX2MEZ3Y9bb9JbfuQh23SjfUpDLB0rfSyBpW61Q9Lz8DQ097JrAKs9kCnEld72xwBDVC7fMrlC4w+3hMaIPP8MHimklgsW4gUGNFCd0M+1MdP+NUTnE403GpK7PhmWuqFKqoOAhllSwvsB//d7BjWKj2bxkuwU2LeJ8QebE79BebWZbj+ZbSjcsVzDZVsO/gIZI8OH9M3UuHnzXsOef5siF8SWFa7Lq+vJ7B+iqHQ9Ntsjf33pHd/3A+LaH76NEs7D1q8WOh2Prlc6F4L49wtQIt8SSpq9IcQEqtIKs6c/1I4Veoy+GG0ZdWHfcgTWoh197Se+ogs9wlsQHBBG3AOshLW+2//HO6N7hFfKe9XGe/bazlqXQy3iM2xE3oYXzo7KzccLl2VxQR+Mfnxp2xG2AMQctAY+q6wnFgGIWhaF7RRHmfOOWhuM0Aw8rTQY6iIvmkTA3u3KMeNiMfPLsvXFyLSCT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
