travis:
  secure:
    BINSTAR_TOKEN: VZW58qpOcwI3QuacfTB7s1mUKI29BFpkS+migj1jnYDTE5X2qx899ie+D9UG4wXbky7zvspJxQHDauXykoOf3neKKL8bWjTpb9b9VVPdPYqj92VLDM0ODCarG6Lij7Lxs/A108EvGdzQv1+3u7izgnqiPNZGWLXKRdO929nnNAl5VrTPwlkcpEXKMKayljoKKu7dZ2IXCvebCYO7NOgC2YHuo09+BVIRxVTrBsTJFS1hD9n3eIkYnJEZUl5zwZkYeXHN73V61Va1gm6FdE0pxdEjOW/0Sda277p71efPkjEzbmo2m80FJ35MTX44gAVfxTZXVLlJeMoQZzJ1EvZO2mqoIPAuzk6BjEJBEjXZ3REqrg1X47jKPHFjhuPVI6zVzSOQMmJKtYFIWBwK3kTr+5eI8JItmEo4J22lKz2uIiAP17A0J0DAzov20kCYLhvQs+/ziZJNoU1y983m9iGLjEdyDx31q3VY+8aLugxzZCdeNc6aI1ljQHO2HUL6sKGgeVg2x8fdRI/P/kXNuujqRwd5BY3OH9y/8vMgnalHSpWpEJMsQBQxs0uHQWwK7gdtdWw+50FzTD4NGfZYJ+A+4Q85gVDtWvN3IB2erjYSZEZeJlTtpVmOWO1VvEZ+op9l3Mlimiq2Ni7IjuzI8U8MiXzdZHm4hf8DubcgRUi/QvU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
