travis:
  secure:
    BINSTAR_TOKEN: Yq5aoN9LFSRqfGFQq6cB9Uan3nsif1BliCKPiE5C4ESDtZ0Ua5bVVK3wQpz6BuqdWUNZpTP4f+7ZXUeViykhbzlm/jtmn94WpvQEDjqTpD2Xu2zTqiu0Jgu/OfAnp0erQdDeWgs++4GC1heYE2SdEvyhd+KRPIsgSSdb6MG2bpjy1nPEfrDEy68xFu2xDjwZU4YHoYEt02r/py96k+H/N4AWHerBgUsx0kbawCqkw1/0vqk9xKP6ud0UN+bNIrQtYcV+d6lIDTwgF4JVu4kvTIQZdBDgvaBoH1tRF2sIZ4SntLG72miu6kNqxosxfkgBn7g2hYyResorYiPYRBV3Pw0v8FS9NHtJ6tQRKQjuhTgumSwsvAcPPNhY2mO+paTXriZcl7BI292FkjeiZ7Qryntl5feB/nxv6kb2ealHCR5fbxzO4sTlDK6pBMqqSowOSoZBvieHZW/b1BJfgFQ59CYwXHQ4YaaJWvDBZEAf09MOkm0swo9H+F25AUfgm2oLgpwBHR9ZpD2Lu0KM3CxSQUmeluyyg2QK0HXH7JUJewdxV/CCCdDLsUeBxjIvHn/dEbi6K0WDt8dz4Hl3+ubZ79UiKB5tkrC3R9jztgU7t1OFm3w1Bwq6XBXECBED2Yudq5++f6ejoSuSacaHm1dpEdX238GJLrK4y3BaRKL5GuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
