travis:
  secure:
    BINSTAR_TOKEN: coSnl/HaddAWfTQXYyNnsuPoMLejZLEcq0Z45IDgGeEalLRjGKq5sxCV90lDpWsb+vAGGvyp9MAZjy1IW9oq9oXaqSwder+tmSZSWUVbBCll4AJ5K3b/TLpfuAY/hly4PJfHCcetwAbmorlNc928vney+U+CsKghtirWlTKb+cbrql5BAWBeHEmt8+tnA+pnLb0pspY80yYWPNQvYMcYdjaALjvVtyC1/eU+8/u36BM303b7hHobHlwLeQp5pDcP7jAdbZS+5tV5wgv5tfHUqSW/vWrgOaZm5iEm1aTJTmVhez7V19l7yzRGfPE2O/u3ZG21nrHn4QsKcBqhm/Qph/HKxAVjNfHI1TIG+fBc9he5BKEBnFNwrfxrjDnnuZtJs7/8qU0opCf5iwDGV3DlveWHcx4ZIuPI4kORXAUjv8tTPG8aL9VJXGrs5G0gQs0P9iRmo0dZfkCKk/tvIJ5HWHmrICG2IQUaHM5IKryMCr2lvmsuqo2mwCrPJW9KGZq4jmGTkunoI4k7QhjlU7SaBhrnIzeYiiO3o33B9eM4l34Z/6Zupm2AvZpOsvj6tKAvDt7mJYmijuY0SktVCFIVzmnIj08PoUAn5WnFRoLiCi3vDO9A5q/Rv1P0ezNo4C/Rhv9BoIVL83IAriHeh1/91w9lYZ/3PPVURWkHVlSGEwk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
